# Generated by Django 2.0.6 on 2018-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='items',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='description',
            field=models.TextField(default=None, max_length=5000),
        ),
    ]
