# Generated by Django 2.0.6 on 2018-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180607_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
