# Generated by Django 2.0.6 on 2018-06-07 14:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0003_auto_20180607_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shopping_list',
            new_name='list',
        ),
    ]
