# Generated by Django 2.0.6 on 2018-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180607_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
