# Generated by Django 2.0.6 on 2018-06-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180607_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total_expenses',
            new_name='month_expenses',
        ),
    ]
