# Generated by Django 2.0.6 on 2018-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180607_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_prioritized',
            field=models.BooleanField(default=False),
        ),
    ]
